art_work/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from art_work.settings import MEDIA_URL

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("mailinglist.urls")),
    path("", include("artworks.urls")),
)





if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

artworks/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path("", views.ArtworkView.as_view()),
    path("filter/", views.FilterArtworkView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name='search'),
    path("event/", views.EventView.as_view(), name="event"),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("<slug:slug>/",views.ArtworkDetailView.as_view(), name = "artwork_detail"),
    path("review/<int:pk>/",views.AddReview.as_view(), name = "add_review"),
    path("artist/<str:slug>/", views.ArtistsDetailView.as_view(), name="artist_detail"),


]

artworks/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(verbose_name="Категория", max_length=250)
    description = models.TextField(verbose_name='Описание')
    url = models.SlugField(max_length=180, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Категории"


class Technic(models.Model):
    name = models.CharField(verbose_name="Техника работы", max_length=250)
    description = models.TextField(verbose_name='Описание')
    url = models.SlugField(max_length=180, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Основная техника"


class Artists(models.Model):
    name = models.CharField(verbose_name="Имя", max_length=300)
    surname = models.CharField(verbose_name="Фамилия", max_length=300)
    patronymic = models.CharField(verbose_name="Отчество", max_length=300,blank=True)
    image = models.ImageField(verbose_name="Изображение", upload_to="artists/")
    location = models.CharField(verbose_name="Адрес", max_length=450)
    technic_favorite = models.ManyToManyField(Technic, verbose_name="Основная техника художника")
    # technic_favorite_addition = models.ForeignKey(Technic, verbose_name="Основная техника художника", on_delete=models.SET_NULL,
    #                                      null=True, default=None)
    age = models.PositiveSmallIntegerField(verbose_name="Возраст")
    description = models.TextField(verbose_name='Биография',max_length=500)
    education = models.TextField(verbose_name='Образование',max_length=250)
    facebook = models.CharField(verbose_name="Facebook", max_length=300, blank=True)
    instagram = models.CharField(verbose_name="Instagram", max_length=300, blank=True)
    site = models.CharField(verbose_name="Сайт", max_length=200, blank=True)
    nft_platform = models.CharField(verbose_name="Платформа NFT", max_length=300, blank=True)
    phone = models.CharField(verbose_name="Номер телефона", max_length=22)

    def __str__(self):
        return self.surname

    def get_full_name(self):
        return self.surname + " " + self.name

    def get_absolute_url(self):
        return reverse('artist_detail', kwargs={"slug":self.surname})


    class Meta:
        verbose_name_plural = "Авторы"



    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Художники"


class Artworks(models.Model):
    name = models.CharField(verbose_name="Название работы", max_length=250)
    description = models.TextField(verbose_name='Описание')
    poster = models.ImageField(verbose_name="Изображение", upload_to="artworks/normal/")
    quality_image = models.ImageField(verbose_name="Изображение-HD", upload_to="artworks/hd/")
    year = models.PositiveSmallIntegerField(verbose_name="Год создания")
    country = models.ForeignKey("Country", verbose_name="Страна", on_delete=models.SET_NULL,null=True)
    location = models.CharField(verbose_name="Месонахождение предмета", max_length=350)
    artist = models.ForeignKey(Artists, verbose_name="Автор", related_name="artwork_artist",on_delete=models.SET_NULL,
                                          null=True) #изменил foreighnkey
    owner = models.CharField(verbose_name="Владелец", max_length=300, blank=True)
    # category_paint = models.ManyToManyField(Technic, verbose_name="Техника", related_name="artwork_technic")
    category = models.ManyToManyField(Category, verbose_name="Категория")
    price = models.PositiveIntegerField(verbose_name="Цена", help_text="Укажите сумму в рублях", default=0)
    in_sale = models.BooleanField(verbose_name="В продаже",default=False)
    signature = models.CharField(verbose_name="Идентификация автора", max_length=300, help_text="Как и где автор оставил свою подпись")
    certificate_of_auth = models.CharField(verbose_name="Подтверждение подлинности", max_length=300, blank=True, help_text="Проверка галереей")
    frame = models.BooleanField(verbose_name="Наличие рамки", default=False)
    size = models.CharField(verbose_name="Размер предмета", max_length=350)
    tags = models.CharField(verbose_name="Теги", max_length=350, default='')
    url = models.SlugField(max_length=180, unique=True)
    draft = models.BooleanField(verbose_name="Черновик", default=False)

    def __str__(self):
        return self.name

    def get_comment(self):
        return self.comment_set.filter(parent__isnull=True)

    def get_absolute_url(self):
        return reverse("artwork_detail", kwargs={"slug":self.url})

    class Meta:
        verbose_name = "Работа"
        verbose_name_plural = "Работы"

class Raitingstar(models.Model):
    value = models.SmallIntegerField(verbose_name="Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"] #Сортировка по значению

class Raiting(models.Model):
    ip = models.CharField("IP-адрес", max_length=15)
    star = models.ForeignKey(Raitingstar, on_delete=models.CASCADE, verbose_name="звезда")
    artworks = models.ForeignKey(Artworks, on_delete=models.CASCADE, verbose_name="работа")

    def __str__(self):
        return f"{self.star} - {self.artworks}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class Comment(models.Model):
    email = models.EmailField()
    name = models.CharField(verbose_name="Имя", max_length=100)
    text = models.TextField(verbose_name="Сообщение", max_length=5000)
    parent = models.ForeignKey("self", verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    artworks = models.ForeignKey(Artworks, verbose_name="Работа", on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

class Country(models.Model):
    label_ru = models.CharField(verbose_name="Название на русском", max_length=140)
    label_en = models.CharField(verbose_name="Название на английском", max_length=140)
    domain = models.CharField(verbose_name="Домен", max_length=10, blank=True, null=True)

    def __str__(self):
        return self.label_ru

    class Meta:
        verbose_name = "Страна"
        verbose_name_plural = "Страны"

class Event(models.Model):
    poster = models.ImageField(verbose_name="Изображение", upload_to="artworks/event/")
    text = models.CharField(verbose_name="Имя", max_length=1000)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Анонс события"
        verbose_name_plural = "Анонсы"

artworks/forms.py
from django import forms
from .models import Comment, Raitingstar, Raiting
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

class ReviewForm(forms.ModelForm):
    '''Форма отзывов'''
    captcha = ReCaptchaField()
    class Meta:
        model = Comment
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name":forms.TextInput(attrs={"class":"form-control border"}),
            "email":forms.EmailInput(attrs={"class":"form-control border"}),
            "text":forms.Textarea(attrs={"class":"form-control border"})
        }

class RaitingForm(forms.ModelForm):
    '''Форма добавления рейтинга'''
    star = forms.ModelChoiceField(
        queryset=Raitingstar.objects.all(), widget=forms.RadioSelect(), empty_label=None
        )
    class Meta:
        model = Raiting
        fields = ("star",)

artworks/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from django.views.generic import ListView, DetailView

from .models import *
from .forms import ReviewForm, RaitingForm
from django.contrib.auth.mixins import LoginRequiredMixin

class CategoryYear():
    """Категории и года создания"""
    def get_category(self):
        return Category.objects.all()

    def get_years(self):
        return Artworks.objects.filter(draft=False).values("year").distinct("year")

class ArtworkView(CategoryYear, ListView):
    '''Работы художников'''
    model = Artworks
    queryset = Artworks.objects.filter(draft=False)
    template_name = "artworks/artworks_list.html"
    paginate_by = 3


class ArtworkDetailView(CategoryYear, DetailView):
    '''Детальная информация по работе'''
    model = Artworks
    template_name = "artworks/artworks_detail.html"
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context["star_form"] = RaitingForm()
        context["form"] = ReviewForm()
        return context



class ArtistsDetailView(CategoryYear, DetailView):
    '''Вывод информации о художнике'''
    model = Artists
    template_name = "artworks/artist.html"
    slug_field = "surname"

class AddReview(View):
    '''Отзывы'''
    model = Artworks
    def post(self,request,pk):
        form = ReviewForm(request.POST)
        artwork = Artworks.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.artworks = artwork
            form.save()
        return redirect(artwork.get_absolute_url())


class FilterArtworkView(CategoryYear, ListView):
    """Фильтр Картин"""
    paginate_by = 2
    def get_queryset(self):
        queryset = Artworks.objects.filter(
            Q(year__in=self.request.GET.getlist("year"))|
            Q(category__in=self.request.GET.getlist("category"))
                                           )
        return queryset

class AddStarRating(View):
    """Добавление рейтинга фильму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RaitingForm(request.POST)
        if form.is_valid():
            Raiting.objects.update_or_create(
                ip=self.get_client_ip(request),
                artworks_id=int(request.POST.get("artwork")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

class Search(ListView):
    """Поиск картины"""
    paginate_by = 2
    def get_queryset(self):
        return Artworks.objects.filter(name__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super(Search, self).get_context_data(*args,**kwargs)
        context["q"] = f'&q={self.request.GET.get("q")}'
        return context

class EventView(LoginRequiredMixin, ListView):
    '''Постеры событий'''
    model = Event
    template_name = "artworks/event.html"
    paginate_by = 3
    raise_exception = True

templates/artworks/artist.html
{% extends 'artworks/base.html' %}
{% load static i18n %}
{% block title %} {{ artists.get_full_name}} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block artwork %}
<div class="container">
    <div class="row">
        <div class="col-sm-offset-2 col-sm-5">
             <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="{{ artists.image.url }}" class="card-img-top" alt="{{artworks.name}}">
        </div>
        <div class="col-sm-5">
            <h4 class="featurette-Заголовок">{{ artists.get_full_name}} </h4>
        <ul>
            <li style="list-style: none">
        <span><b>{% trans "Дата рождения" %}:</b><span> {{ artists.age}}</span></span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Образование" %}:</b><span> {{ artists.education}}</span></span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Локация" %}:</b><span> {{ artists.location }}</span></span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Техника работы" %}:</b><span>  {% for technic_paint in artists.technic_favorite.all %}
                <span>{{ technic_paint.name }}</span>
                {% if artists.technic_favorite.all.count > 1 %}
                    <span> </span>
                {% endif %}
            {% endfor %}</span>
                </span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Инстаграм" %}:</b><a href="{{ artists.instagram }}"> {{ artists.instagram }}</a></span>
            </li>
            <li style="list-style: none">
        <span "><b>{% trans "Сайт" %}:</b><a href="{{ artists.site }}"> {{ artists.site }}</a></span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "NFT-платформа" %}:</b><a href="{{ artists.nft_platform }}"> {{ artists.nft_platform }}</a></span>
            </li>
        </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
            <span><b>{% trans "Биография" %}:</b><span> {{ artists.description }}</span></span>
        </div>
    </div>
</div>


{#    <div class="left-ads-display col-lg-12">#}
{#    {% include 'include/comment.html' %}#}
{#    </div>#}
{% endblock artwork %}

templates/artworks/artworks_detail.html
{% extends 'artworks/base.html' %}
{% load static i18n %}
{#<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">#}
{% block title %} {{ artworks.name}} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block artwork %}
  <div class="left-ads-display col-lg-8">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h3 class="featurette-Заголовок">"{{ artworks.name}}" </h3>
{#          {% for artist in artworks.artist.all %}#}
             <a href="{{ artworks.artist.get_absolute_url }}">Художник: {{ artworks.artist.get_full_name}}</a>
{#          {% endfor %}#}
        <ul>
            <li style="list-style: none">
        <span><b>{% trans "Описание" %}:</b><span>{{ artworks.description|safe }}</span></span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Техника" %}:</b>
            {% for tech in artworks.category.all %}
                <span>{{ tech }}</span>
                {% if artworks.category.all.count > 1 %}
                    <span>,</span>
                {% endif %}
            {% endfor %}
        </span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Страна"%}:</b> {{ artworks.country  }}</span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Местонахождение работы"%}:</b> {{ artworks.location  }}</span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Год создания работы"%}:</b>  {{ artworks.year }}</span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Стоимость"%}:</b>  <i class="lead">{{ artworks.price }} &#8381;</i></span>
            </li>
            <li style="list-style: none">
        <span title="Как и где автор оставил свою подпись"><b>{% trans  "Идентификация автора"%}:</b>  {{ artworks.signature }}</span>
            </li>
            <li style="list-style: none">
        <span title="Ссылка на NFT-маркетплейс"><b>{% trans "NFT токен"%}:</b>  <a href="/">{{ artworks.certificate_of_auth }}</a></span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Размер работы" %}:</b>  {{ artworks.size }} cm.</span>
            </li>
            <li style="list-style: none">
        <span><b>{% trans "Теги" %}:</b>  {{ artworks.tags }}</span>
            </li>
        </ul>
        <div>
            <form action="{% url 'add_rating' %}" method="post" name="rating">
                <b>{% trans "Рейтинг" %}</b>
                {% csrf_token %}
                <input type="hidden" value="{{ artworks.id }}" name="artwork">
{#                {{ star_form }}#}
                <span class="rating">
                    {% for k, v in star_form.fields.star.choices %}
                        <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                        <label for="rating{{ v }}">{{ k }}</label>
                    {% endfor %}
                </span>
                <span class="editContent">4.0</span>
            </form>
        </div>

      </div>

      <div class="col-md-5 order-md-1">
        <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="{{ artworks.poster.url }}" class="card-img-top" alt="{{artworks.name}}">

      </div>

    </div>
    <br>
    <div class="left-ads-display col-lg-12">
    {% include 'include/comment.html' %}
    </div>
{#     <script>#}
{#        function addReview(name, id) {#}
{#            document.getElementById("contactparent").value = id;#}
{#            document.getElementById("contactcomment").innerText = `${name}, `#}
{#        }#}
{##}
{#    </script>#}
{% endblock artwork %}

templates/artworks/artworks_list.html
{% extends 'artworks/base.html' %}
{% load static i18n %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block artwork %}
  <div class="left-ads-display col-lg-9">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {%  for artwork in artworks_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" style="object-fit: contain"  width="100%" src="{{ artwork.poster.url }}" class="card-img-top" alt="...">
            <div class="card-body">
              <p class="card-text" > {{ artwork.name }}</p>
              <p class="card-text">{{ artwork.artist.get_full_name }}</p>
              <p class="card-text">{{ artwork.description|safe }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href = '{{ artwork.get_absolute_url }}';">{% trans "Посмотреть"  %}</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">{% trans "Купить"  %}</button>
                </div>
{#                <small class="text-muted">9 минут</small>#}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
      <div class="align-content-center col-lg-9" >
          <br>
        {% include 'artworks/pagination.html' %}
    </div>
</div>
{% endblock artwork %}

templates/artworks/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
                {% include 'include/sidebar.html' %}
            {% endblock sidebar %}

            </div>
            {% block artwork %}
            {% endblock artwork %}
            {% block event %}
            {% endblock event %}

        </div>

        </div>
    </section>
{% endblock content %}




{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{##}
{#{% endblock content %}#}

templates/artworks/event.html
{% extends 'artworks/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block sidebar %}
{% endblock sidebar %}
{% block event %}
  <div class="left-ads-display col-lg-12">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        {%  for event in event_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" style="object-fit: contain"  width="100%" src="{{ event.poster.url }}" class="card-img-top" alt="...">
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</div>
        <div class="align-content-center col-lg-7" >
        {% include 'artworks/pagination.html' %}
    </div>
{% endblock event %}

templates/artworks/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">

    <li class="page-item ">
     {% if page_obj.has_previous %}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}{{ q }}{% endif %}{% if request.GET.year %}&year={{request.GET.year}}{% endif %}{% if request.GET.category %}&category={{request.GET.category}}{% endif %}">Previous</a>
     {% else %}
        <a class="page-link disabled" href="?page=1{% if request.GET.q %}{{ q }}{% endif %}{% if request.GET.year %}{{ year }}{% endif %}{% if request.GET.category %}&year={{request.GET.category}}{% endif %}{% if request.GET.category %}&category={{request.GET.category}}{% endif %}">First</a>
    {% endif %}
    </li>

    <li class="page-item"><a class="page-link" href="?page={{ page_obj.number }}{% if request.GET.q %}{{ q }}{% endif %}{% if request.GET.year %}&year={{request.GET.year}}{% endif %}{% if request.GET.category %}&category={{request.GET.category}}{% endif %}">{{ page_obj.number }}</a></li>
    <li class="page-item">
    {% if page_obj.has_next %}
      <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}{{q}}{% endif %}{% if request.GET.year %}&year={{request.GET.year}}{% endif %}{% if request.GET.category %}&category={{request.GET.category}}{% endif %}">Next</a></li>
    {% else %}
      <a  class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}{{q}}{% endif %}{% if request.GET.year %}&year={{request.GET.year}}{% endif %}{% if request.GET.category %}&category={{request.GET.category}}{% endif %}">Last </a>
    {% endif %}
  </ul>
</nav>